# use minimal nginx alpine image for proxying to hugo and decap-cms containers
FROM quay.io/giantswarm/nginx-unprivileged:1.24-alpine
EXPOSE 8081
USER 0

# configure CMS redirect /admin /auth /callback -> decap, / -> hugo
COPY proxy-cms-admin.conf /etc/nginx/conf.d/proxy-cms-admin.conf

# copy in staticly built hugo site from build step above
#VOLUME /usr/share/nginx/html
USER 101
