name: Render RFCs and create/update PR on changes

on:
  # In case the `push` trigger does not work, try regularly
  schedule:
    - cron: "0 12,17 * * MON-FRI"

  push:

jobs:
  render-rfcs-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: handbook

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'giantswarm/rfc'
          path: rfc

      - name: Render RFCs
        env:
          RFCS_DIR: "${{ github.workspace }}/rfc"
        run: |
          make rfcs

          # https://github.com/peter-evans/create-pull-request/issues/783
          sudo chown -R $USER:$USER content/docs/rfcs
        working-directory: "${{ github.workspace }}/handbook"

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v5
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          path: handbook
          commit-message: "Update rendered RFCs"
          title: "Update generated RFCs content"
          branch: update-generated-rfcs-content
          body: |
            This PR has been created automatically by the 'Render RFCs and create/update PR on changes' GitHub workflow
            to keep rendered RFCs in the handbook up to date.

            Please review and merge, or check in `#sig-docs` chat if something is wrong.
          team-reviewers: |
            giantswarm/sig-docs
